### ISSUE TITLE
How do I know what containers to start?

### ISSUE THREAD

**Issue by flock3** [venting/silo#1]
## The problem

When a new server is brought online, and the silo agent is started, it needs to go and fetch the configuration that will allow it to spin up the containers it needs to for that service.

## Possible solution 1 - Config files

The container could be given environment configuration to tell it where to get it's stack config
```
docker run venting/silo-agent -e STACK_FILE=http://my-bucket-name.s3.amazonaws.com/test.yml
```

```
docker run venting/silo-agent -e STACK_FILE=github.com/venting/silo-example/test.yml -e STACK_REVISION=e5ef2ceb
```

## Possible solution 2 - Central command & control server

```
docker run venting/silo-agent -e COMMAND_HOST=http://10.0.0.1/ -e STACK_NAME=test
```

Perhaps a combination of solutions 1 and two would be a nice way to go. It would allow people to bring up very simple stacks (i.e. ones that change infrequently) without any headache of having a central management server.

Going with option 1 only would mean that the user would have to change the launch configuration of their services to point at a new file/revision and then launch more servers with the new configuration before killing off the olds ones, if they needed an upgrade without service interruption.

**Comment by Rucknar** [comment]
If it's simply connecting to an end-point to retrieve a file. We could potentially present it in a file storage manner so that it's the same command if you connect to a share, or a server?
